server:
  port: 8888

management:
  context-path: /admin
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mbdemirkan/microservices
          search-paths:
              - Configurations
          basedir: target/config

